tasks: 
  - task: render as application
    module: src\modules\bunny-dev\modules\app-builder
    description: 
      there is a button `render as application`
      this should have its own layout. 
      in that layout has button to go back to its meta data on app builder.
      like it simulates a full application outside of app-builder module.

  - task: populate selections for select field in ai generation
    module: src\modules\bunny-dev\modules\app-builder
    description:
      when type of field is select the ai generate the options for selects 
      instead of just empty selection field.


  - task: Improve the view mode. 
    module: src\modules\bunny-dev\modules\app-builder
    description:
      Reference the laravel filament on rendering relationship.
      i want exact implementation of laravel filament on how it connect its resources

  
  - task: Seperate Database for rendered application
    module: src\modules\bunny-dev\modules\app-builder
    description:
      i want to simulate that rendered app saved or recorded value in rendered app has
      seperate Database

  - task: add more meta data for actual seperate application configuration
    module: src\modules\bunny-dev\modules\app-builder
    description:
      for app render application meta data. this configuration to configure when app is render
      what would be app title and so on. 

  - task: Enhance API Design
    module: src\modules\bunny-dev\modules\api-design
    sub_tasks:
      - task: make delete button an icon button.
      - task: the operation bar should be set max height with virtual scroll.
      - task: bun add @faker-js/faker the return object should also selection what item to fake it.
        notes: 
          the ai generation should select the fake item type too.
  - task: Improve layout css of display instead of looking purple i want very good rendering layout design with background (only affected bunny-dev  module)
    module: src\modules\bunny-dev\modules\diagram-builder
  - task: Dynamic Diagram builder Editor
    module: src\modules\bunny-dev\modules\diagram-builder
    description:
      when i change the type flowchart, sequence or any other mode.
      the editor field always stick to nodes and edges. that only works to flowchart.
      but editing other diagram it lacks of capacity and functionality to edit other types of diagram.

      each type should have its own editor fields. 

      when there is existing data prevent on changing types. it needs to set types on creation of diagram

      direction is not working it does not change the diagram.
  - task: Improve Sidebar actions
    module: all
    description:
      improve sidebar actions. the delete action button make it icon button of delete with tooltip

  - task: Add meaningful content ai generation
    module: src\modules\bunny-dev\modules\architecture
    concern:
      when i make ai generation. it likes of meaningful sections - generated document. 
      it should be very highly information. like 300-500 words per section and well defined. 
      well defined structures of sections. In editor use wyiswyg instead of just a textarea

  
  - task: In HTML. Add View and Export to HTML
    module: src\modules\bunny-dev\modules\architecture
    description:
      it has capable to make a html with good tailwind css output design with md to html

  - task: Improve Task Modal
    module: src\modules\bunny-dev\modules\project-management
    sub_task:
      task: when writing description put a label that field is unsaved then underneath description add saved button when in update mode.
      task: remove save task button in modal.
      task: when select field is change save it on the record when in update mode.
      task: when i write a comment and click comment. the scroll move where my new comment was.
      task: when in create mode add create task button in modal the auto update records is only on update mode and the save description button only on update mode.
      task: consider if assignee member id and story points is needed field. if not remove it.
      task: In drag and drop. i had capable to move which position or change position of task what task is switcing on.
  - task: Project Management Settings
    module: src\modules\bunny-dev\modules\project-management
    description:
      add settings button. one settings that attach to the board settings and other one is global settings.
      in board settings i could capable add custom fields and rename board.
      capable to adjust add sections and move order of sections

      in global setttings i could have capable to move the order of the board and rename it


  - task: File Management Improvement
    module: src\modules\bunny-dev\modules\file-management
    sub_task:
      task: support upload multimedia upload and add modal viewer for it.
      task: add multiple select toggle and group move, copy, download or delete.
      task: password protected file. you can not edit, view or download. if file is password protected. 
      task: you can remove password protected by matching the password.
    






    