// ─────────────────────────────────────────────────────────────────────────────
// CatalogOpenCodeGoCalculator.Dictionary.ts
//
// ⚠️  AUTO-GENERATED — DO NOT EDIT MANUALLY.
//
// Generated by the OpenCode Go Calculator code generator:
//   Catalog → OpenCode Go Calculator → Code Generator
// Copy the full generated output over this file whenever pricing changes.
//
// Generated at: 2026-09-10T18:18:21.425Z
// Models: 36
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single OpenCode Go model's pricing and monthly subscription quota.
 */
export interface OpenCodeGoModelPricing {
  /** Display name of the model. */
  name: string;
  /** Input price in USD per 1M tokens. */
  input: number;
  /** Output price in USD per 1M tokens. */
  output: number;
  /** Cached read price in USD per 1M tokens, or null when not offered. */
  cachedRead: number | null;
  /** Cached write price in USD per 1M tokens, or null when not offered. */
  cachedWrite: number | null;
  /** Monthly subscription quota in USD. */
  monthlyQuota: number;
}

export const OPEN_CODE_GO_PRICING: OpenCodeGoModelPricing[] = [
  { name: "GLM-5.3-Flash", input: 0.15, output: 0.5, cachedRead: 0.03, cachedWrite: null, monthlyQuota: 60 },
  { name: "GLM-5.3", input: 1.4, output: 4.4, cachedRead: 0.26, cachedWrite: null, monthlyQuota: 15 },
  { name: "GLM-5.2", input: 1.4, output: 4.4, cachedRead: 0.26, cachedWrite: null, monthlyQuota: 60 },
  { name: "GLM-5.1", input: 1.4, output: 4.4, cachedRead: 0.26, cachedWrite: null, monthlyQuota: 60 },
  { name: "Kimi K3", input: 3, output: 15, cachedRead: 0.3, cachedWrite: null, monthlyQuota: 15 },
  { name: "Kimi K2.7 Code", input: 0.95, output: 4, cachedRead: 0.19, cachedWrite: null, monthlyQuota: 60 },
  { name: "Kimi K2.6", input: 0.95, output: 4, cachedRead: 0.16, cachedWrite: null, monthlyQuota: 60 },
  { name: "LongCat-2.0", input: 0.3, output: 1.2, cachedRead: 0.006, cachedWrite: null, monthlyQuota: 60 },
  { name: "MiMo V2.5", input: 0.14, output: 0.28, cachedRead: 0.0028, cachedWrite: null, monthlyQuota: 60 },
  { name: "MiMo V2.5 Pro", input: 0.435, output: 0.87, cachedRead: 0.003625, cachedWrite: null, monthlyQuota: 15 },
  { name: "MiniMax M3", input: 0.3, output: 1.2, cachedRead: 0.06, cachedWrite: null, monthlyQuota: 60 },
  { name: "MiniMax M2.7", input: 0.3, output: 1.2, cachedRead: 0.06, cachedWrite: 0.375, monthlyQuota: 60 },
  { name: "MiniMax M2.5", input: 0.3, output: 1.2, cachedRead: 0.06, cachedWrite: 0.375, monthlyQuota: 60 },
  { name: "Muse Spark 1.3 Contributor", input: 0.1, output: 0.2, cachedRead: 0.002, cachedWrite: null, monthlyQuota: 60 },
  { name: "Muse Spark 1.2 Contributor", input: 0.1, output: 0.2, cachedRead: 0.002, cachedWrite: null, monthlyQuota: 60 },
  { name: "Qwen3.8 Max", input: 2, output: 6, cachedRead: 0.25, cachedWrite: 2.5, monthlyQuota: 15 },
  { name: "Qwen3.8 Flash", input: 0.15, output: 0.47, cachedRead: 0.016, cachedWrite: 0.2, monthlyQuota: 30 },
  { name: "Qwen3.7 Max", input: 2.5, output: 7.5, cachedRead: 0.5, cachedWrite: 3.125, monthlyQuota: 30 },
  { name: "Qwen3.7 Plus (≤ 256K tokens)", input: 0.4, output: 1.6, cachedRead: 0.04, cachedWrite: 0.5, monthlyQuota: 60 },
  { name: "Qwen3.7 Plus (> 256K tokens)", input: 1.2, output: 4.8, cachedRead: 0.12, cachedWrite: 1.5, monthlyQuota: 60 },
  { name: "Qwen3.6 Plus (≤ 256K tokens)", input: 0.5, output: 3, cachedRead: 0.05, cachedWrite: 0.625, monthlyQuota: 60 },
  { name: "Qwen3.6 Plus (> 256K tokens)", input: 2, output: 6, cachedRead: 0.2, cachedWrite: 2.5, monthlyQuota: 60 },
  { name: "DeepSeek V4.1 Flash (Off-Peak)", input: 0.15, output: 0.6, cachedRead: 0.003, cachedWrite: null, monthlyQuota: 15 },
  { name: "DeepSeek V4.1 Flash (Peak)", input: 0.3, output: 1.2, cachedRead: 0.006, cachedWrite: null, monthlyQuota: 15 },
  { name: "DeepSeek V4 Pro (Off-Peak)", input: 0.66, output: 1.98, cachedRead: 0.022, cachedWrite: null, monthlyQuota: 15 },
  { name: "DeepSeek V4 Pro (Peak)", input: 1.32, output: 3.96, cachedRead: 0.044, cachedWrite: null, monthlyQuota: 15 },
  { name: "DeepSeek V4 Flash (Off-Peak)", input: 0.15, output: 0.6, cachedRead: 0.003, cachedWrite: null, monthlyQuota: 30 },
  { name: "DeepSeek V4 Flash (Peak)", input: 0.3, output: 1.2, cachedRead: 0.006, cachedWrite: null, monthlyQuota: 30 },
  { name: "DeepSeek V4 Flash Vision Exp (Off-Peak)", input: 0.15, output: 0.6, cachedRead: 0.003, cachedWrite: null, monthlyQuota: 15 },
  { name: "DeepSeek V4 Flash Vision Exp (Peak)", input: 0.3, output: 1.2, cachedRead: 0.006, cachedWrite: null, monthlyQuota: 15 },
  { name: "Hy4 preview", input: 0.834, output: 2.501, cachedRead: 0.042, cachedWrite: null, monthlyQuota: 30 },
  { name: "Hy3", input: 0.14, output: 0.58, cachedRead: 0.035, cachedWrite: null, monthlyQuota: 60 },
  { name: "Grok 4.6 (≤ 200K tokens)", input: 2, output: 6, cachedRead: 0.5, cachedWrite: null, monthlyQuota: 15 },
  { name: "Grok 4.6 (> 200K tokens)", input: 4, output: 12, cachedRead: 1, cachedWrite: null, monthlyQuota: 15 },
  { name: "GPT 5.6 Luna (≤ 272K tokens)", input: 0.2, output: 1.2, cachedRead: 0.02, cachedWrite: 0.25, monthlyQuota: 15 },
  { name: "GPT 5.6 Luna (> 272K tokens)", input: 0.4, output: 1.8, cachedRead: 0.04, cachedWrite: 0.5, monthlyQuota: 15 },
];
