// bc.persona.entity.ts
//
// BCCasePersona — the "customer" a user trains against. Traits are defined by
// the user; the psychological profile, triggers, preferences and communication
// style are AI-generated by the Persona Architect.
//
// List-ish fields (traits/triggers/preferences) are stored as comma-separated
// strings so Bunny's string-oriented form handles them cleanly; they are parsed
// into arrays when fed to the AI.

export interface BCCasePersona {
  id?: number;
  /** Human-readable label, e.g. "Impatient VIP" */
  name: string;
  /** Comma-separated trait labels, e.g. "Impatient, Confused, High-Value" */
  traits: string;
  /** Free-form description of the persona */
  description?: string;
  /** AI-generated psychological profile (motivations, stress points) */
  psychologicalProfile?: string;
  /** Comma-separated triggers that escalate the persona */
  triggers?: string;
  /** Comma-separated preferences the persona values */
  preferences?: string;
  /** AI-generated communication style guidance */
  communicationStyle?: string;
  /** Short AI summary of the persona */
  aiSummary?: string;
  createdAt?: number;
  updatedAt?: number;
}

/** Structured output of the Persona Architect AI generation. */
export interface BCGeneratedPersonaProfile {
  psychologicalProfile: string;
  triggers: string[];
  preferences: string[];
  communicationStyle: string;
  aiSummary: string;
}

/** Parse a comma-separated string into a trimmed list. */
export function bcPersonaParseList(value?: string): string[] {
  if (!value) return [];
  return value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

/** Join an array (or comma-separated string) into a display string. */
export function bcPersonaJoinList(value: unknown): string {
  if (Array.isArray(value)) return value.join(", ");
  return typeof value === "string" ? value : "";
}
